name: Dev Build and Push Container

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

env:
  AWS_ECR_REPO: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/platform-console-ui

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      package-version: ${{ steps.get-version.outputs.package-version }}
    steps:
      - name: Configure AWS Credentials
        run: |
          echo "building dev"

  update-dev-manifest:
    runs-on: ubuntu-latest
    environment: Dev
    needs: build
    steps:
      - name: Configure AWS Credentials
        run: |
          echo "updating dev manifest"