name: Dev Build and Push Container

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      package-version: ${{ steps.get-version.outputs.package-version }}
    steps:
      - name: Configure AWS Credentials
        run:
          echo "building dev package"

  update-dev-manifest:
    runs-on: ubuntu-latest
    environment: Dev
    needs: build
    steps:
      - name: Configure AWS Credentials
        run: |
          echo "dev manifest update"