name: Create Prerelease Draft

on:
  schedule:
    - cron: '0 10 * * 1'
  workflow_dispatch:
  workflow_call:

jobs:
  draft-prerelease:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: |
          delimiter=$(date +'%Y-%b-%d')
          echo "::set-output name=date-string::$delimiter"

      - name: Get SHA
        id: get-sha
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "::set-output name=short-sha::$(git rev-parse --short HEAD)"

      - name: Get version
        id: get-version
        run: |
          TAG_NAME=$(npm run get-version -s)-${{ steps.get-sha.outputs.short-sha }}
          if [ "$(git ls-remote --exit-code --tags origin $TAG_NAME)" ]; then
            echo "::set-output name=package-version::$TAG_NAME-${{ github.run_number }}"
          else
            echo "::set-output name=package-version::$TAG_NAME"
          fi

      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACTIONS_TOKEN_APP_ID }}
          private_key: ${{ secrets.ACTIONS_TOKEN_PRIVATE_KEY }}

      - name: Create tag
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: POST /repos/{repo}/git/refs
          repo: ${{ github.repository }}
          ref: 'refs/tags/${{ steps.get-version.outputs.package-version }}'
          sha: ${{ steps.get-sha.outputs.sha }}

      - name: Create prerelease
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: POST /repos/{repo}/releases
          repo: ${{ github.repository }}
          name: ${{ steps.get-date.outputs.date-string }}
          tag_name: ${{ steps.get-version.outputs.package-version }}
          target_commitish: ${{ steps.get-sha.outputs.sha }}
          generate_release_notes: true
          prerelease: true
          draft: true