name: Enable Release Workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  generate-token:
    runs-on: ubuntu-latest
    outputs:
      GITAPP_TOKEN: ${{ steps.generate-token.outputs.token }}

    steps:
    - name: Generate token
      id: generate-token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.ACTIONS_TOKEN_APP_ID }}
        private_key: ${{ secrets.ACTIONS_TOKEN_PRIVATE_KEY }}

  enable-create-prerelease-draft-workflow:
    runs-on: ubuntu-latest
    needs: generate-token
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITAPP_TOKEN: ${{ needs.generate-token.outputs.GITAPP_TOKEN }}

    steps:
    - name: Enable cd-create-prerelease-draft Workflow
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ env.GITAPP_TOKEN }}
      with:
        route: PUT /repos/{repo}/actions/workflows/{workflow_id}/enable
        repo: ${{ github.repository }}
        workflow_id: cd-create-prerelease-draft.yml

  enable-publish-prerelease-workflow: 
    runs-on: ubuntu-latest
    needs: generate-token
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITAPP_TOKEN: ${{ needs.generate-token.outputs.GITAPP_TOKEN }}

    steps:
    - name: Enable cd-publish-prerelease Workflow
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ env.GITAPP_TOKEN }}
      with:
        route: PUT /repos/{repo}/actions/workflows/{workflow_id}/enable
        repo: ${{ github.repository }}
        workflow_id: cd-publish-prerelease.yml

  enable-promote-release-workflow: 
    runs-on: ubuntu-latest
    needs: generate-token
    env:
      GITHUB_TOKEN: ${{ github.token }}
      GITAPP_TOKEN: ${{ needs.generate-token.outputs.GITAPP_TOKEN }}

    steps:
    - name: Enable cd-promote-release Workflow
      uses: octokit/request-action@v2.x
      env:
        GITHUB_TOKEN: ${{ env.GITAPP_TOKEN }}
      with:
        route: PUT /repos/{repo}/actions/workflows/{workflow_id}/enable
        repo: ${{ github.repository }}
        workflow_id: cd-promote-release.yml