name: Hotfix Deployment Release

on:
  pull_request:
    types: [closed]
    branches:    
      - main
  workflow_dispatch:

jobs:
  get-source-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    outputs:
      SOURCE_BRANCH: $GITHUB_HEAD_REF
  
  deploy-to-dev:
    needs: get-source-branch
    if: needs.get-source-branch.outputs.SOURCE_BRANCH == 'hotfix'
    uses: Matth-Ng/hello-world/.github/workflows/cd-build.yml@hotfix
    
  # create-prerelease:
  #   needs: deploy-to-dev
  #   uses: Matth-Ng/hello-world/.github/workflows/cd-create-prerelease-draft.yml@hotfix

  # publish-prerelease:
  #   needs: create-prerelease
  #   env:
  #     PUBLISH-PRERELEASE: ${{ needs.set-reusable-workflow-var.outputs.PUBLISH-PRERELEASE }}
  #   uses: Matth-Ng/hello-world/.github/workflows/cd-publish-prerelease.yml@hotfix
  #   with:
  #     latest: true

  # promote-release:
  #   needs: publish-prerelease
  #   uses: Matth-Ng/hello-world/.github/workflows/cd-promote-release.yml@hotfix