name: Hotfix Deployment Release

on:
  pull_request:
    types: [closed]
    branches:    
      - main
  workflow_dispatch:

jobs:
  get-source-branch:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    outputs:
      SOURCE_BRANCH: ${{ steps.get-source-info.outputs.head-ref }}
      SOURCE_SHA: ${{ steps.get-source-info.outputs.head-sha }}
    steps:
      - name: Get Source Info
        id: get-source-info
        run: |
          echo "::set-output name=head-ref::$GITHUB_HEAD_REF"
          echo "::set-output name=head-sha::$GITHUB_SHA"
  
  deploy-to-dev:
    needs: get-source-branch
    if: needs.get-source-branch.outputs.SOURCE_BRANCH == 'hotfix'
    uses: Matth-Ng/hello-world/.github/workflows/cd-build.yml@${{needs.get-source-branch.outputs.SOURCE_SHA}}
    
  create-prerelease:
    needs: [deploy-to-dev, deploy-to-dev]
    uses: Matth-Ng/hello-world/.github/workflows/cd-create-prerelease-draft.yml@${{needs.get-source-branch.outputs.SOURCE_SHA}}

  publish-prerelease:
    needs:  [deploy-to-dev, deploy-to-dev, create-prerelease]
    uses: Matth-Ng/hello-world/.github/workflows/cd-publish-prerelease.yml@${{needs.get-source-branch.outputs.SOURCE_SHA}}
    with:
      latest: true

  promote-release:
    needs: [deploy-to-dev, deploy-to-dev, create-prerelease, publish-prerelease]
    uses: Matth-Ng/hello-world/.github/workflows/cd-promote-release.yml@${{needs.get-source-branch.outputs.SOURCE_SHA}}