name: Hotfix Deployment Release

on:
  push:
    branches:
      - hotfix
  workflow_dispatch:

jobs:
  set-reusable-workflow-var:
    outputs:
      DEPLOY-TO-DEV: ${{ steps.set-variable.outputs.deploy-to-dev }}
      CREATE-PRERELEASE: ${{ steps.set-variable.outputs.create-prerelease }}
      PUBLISH-PRERELEASE: ${{ steps.set-variable.outputs.publish-prerelease }}
      PROMOTE-RELEASE: ${{ steps.set-variable.outputs.promote-release }}
    steps:
      - name: Set Variable
        id: set-variable
        run: |
          REPO=${{ github.repository }}
          echo "::set-output name=deploy-to-dev::$REPO/.github/workflows/cd-build.yml@hotfix"
          echo "::set-output name=create-prerelease::$REPO/.github/workflows/cd-create-prerelease-draft.yml@hotfix"
          echo "::set-output name=publish-prerelease::$REPO/.github/workflows/cd-publish-prerelease.yml@hotfix"
          echo "::set-output name=promote-release::$REPO/.github/workflows/cd-promote-release.yml@hotfix"

  deploy-to-dev:
    env:
      RELEASE_ID: ${{ needs.set-reusable-workflow-var.outputs.DEPLOY-TO-DEV }}
    uses: ${{ env.RELEASE_ID }}
    
  create-prerelease:
    needs: deploy-to-dev
    env:
      CREATE-PRERELEASE: ${{ needs.set-reusable-workflow-var.outputs.CREATE-PRERELEASE }}
    uses: ${{ env.CREATE-PRERELEASE }}
    #uses: "${{ github.repository }}/.github/workflows/cd-create-prerelease-draft.yml@hotfix"

  publish-prerelease:
    needs: create-prerelease
    env:
      PUBLISH-PRERELEASE: ${{ needs.set-reusable-workflow-var.outputs.PUBLISH-PRERELEASE }}
    uses: ${{ env.PUBLISH-PRERELEASE }}
    # "${{ github.repository }}/.github/workflows/cd-publish-prerelease.yml@hotfix"
    with:
      latest: true

  promote-release:
    needs: publish-prerelease
    env:
      PROMOTE-RELEASE: ${{ needs.set-reusable-workflow-var.outputs.PROMOTE-RELEASE }}
    uses: ${{ env.PROMOTE-RELEASE }}
    #uses: "${{ github.repository }}/.github/workflows/cd-promote-release.yml@hotfix"

  merge-to-main-pr:
    runs-on: ubuntu-latest
    needs: promote-release

    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACTIONS_TOKEN_APP_ID }}
          private_key: ${{ secrets.ACTIONS_TOKEN_PRIVATE_KEY }}

      - name: Create PR
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: POST /repos/{repo}/pulls
          repo: ${{ github.repository }}
          title: "Hot fix"
          head: hotfix
          base: main
          body: "Merging hot fix changes into main"
          maintainer_can_modify: true