name: Hotfix Deploy to Utility

on:
  pull_request_review:
    types: [submitted]
  workflow_dispatch:

jobs:

  check-workflow:
    if: github.event.pull_request.head.ref == 'hotfix' && github.event.review.state == 'approved'
    outputs:
      DRAFT_STATE: ${{ steps.create-workflow-enabled.outputs.value }}
    runs-on: ubuntu-latest

    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACTIONS_TOKEN_APP_ID }}
          private_key: ${{ secrets.ACTIONS_TOKEN_PRIVATE_KEY }}
          
      - name: Get cd-create-prerelease-draft workflow
        id: create-workflow-info
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: GET /repos/{repo}/actions/workflows
          repo: ${{ github.repository }}
          workflow_id: cd-create-prerelease-draft.yml
      
      - name: Check if create workflow enabled
        id: create-workflow-enabled
        uses: sergeysova/jq-action@v2
        with:
          cmd: |
            cat << EOF > json.txt
            ${{ steps.create-workflow-info.outputs.data }}
            EOF
            sed -e "s/'//g" json.txt > newjson.txt
            JSON=$(cat newjson.txt)
            echo "$JSON" | jq -r '.workflows[] | select(.name=="Create Prerelease Draft") | .state'

  deploy-to-dev:
    if: github.event.review.state == 'approved' && needs.check-workflow.outputs.DRAFT_STATE == 'active'
    needs: check-workflow
    uses: Matth-Ng/hello-world/.github/workflows/cd-build.yml@hotfix
    
  create-prerelease:
    needs: deploy-to-dev
    uses: Matth-Ng/hello-world/.github/workflows/cd-create-prerelease-draft.yml@hotfix
    with:
      disable-workflow: true
      generate-notes: false
    secrets: inherit

  publish-prerelease:
    needs: create-prerelease
    uses: Matth-Ng/hello-world/.github/workflows/cd-publish-prerelease.yml@hotfix
    with:
      disable-workflow: true
      latest: true
    secrets: inherit

  promote-release:
    needs: publish-prerelease
    uses: Matth-Ng/hello-world/.github/workflows/cd-promote-release.yml@hotfix
    with:
      disable-workflow: true
    secrets: inherit