name: Hotfix Merge and Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: set matrix
        id: set-matrix
        run: |
          echo "::set-output name=matrix::[\"a\", \"b\", \"c\"]"

   build:
    needs: [ job1 ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - name: matrix test
        run: |
          echo "${{ matrix.value }}"
