name: Hotfix Deploy to Utility

on:
  pull_request_review:
    types: [submitted]
    branches:    
      - hotfix
  workflow_dispatch:

jobs:
  deploy-to-dev:
    if: github.event.review.state == 'approved'
    uses: Matth-Ng/hello-world/.github/workflows/cd-build.yml@hotfix
    
  create-prerelease:
    needs: deploy-to-dev
    uses: Matth-Ng/hello-world/.github/workflows/cd-create-prerelease-draft.yml@hotfix

  publish-prerelease:
    needs: create-prerelease
    uses: Matth-Ng/hello-world/.github/workflows/cd-publish-prerelease.yml@hotfix
    with:
      latest: true

  promote-release:
    needs: publish-prerelease
    uses: Matth-Ng/hello-world/.github/workflows/cd-promote-release.yml@hotfix