name: Hotfix Deployment Release

on:
  # push:
  #   branches:
  #     - hotfix
  workflow_dispatch:

jobs:
  deploy-to-dev:
    uses: ./.github/workflows/cd-build.yml
    with:
      latest-date: true
    
  deploy-to-staging:
    needs: deploy-to-dev
    uses: ./.github/workflows/cd-create-prerelease.yml
    with:
      latest-date: true

  deploy-to-utility:
    needs: deploy-to-staging
    uses: ./.github/workflows/cd-promote-prerelease.yml
    with:
      workflow: true
  
  # redeploy-to-lower-tier:

  #   runs-on: ubuntu-latest
  #   needs: deploy-to-utility
  #   env:
  #     GITHUB_TOKEN: ${{ github.token }}

  #   steps:
  #     - name: Disable hotfix deployment release
  #       if: github.event.inputs.latest == 'true'
  #       shell: bash
  #       run: |
  #         gh workflow disable -R $GITHUB_REPOSITORY "hotfix Deployment Release"

  # merge-main:
  #   runs-on: ubuntu-latest
