name: Hotfix Merge and Create Release

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-to-dev:
    if: needs.get-source-branch.outputs.SOURCE_BRANCH == 'hotfix'
    uses: .github/workflows/cd-build.yml
    
  create-prerelease:
    needs: deploy-to-dev
    uses: .github/workflows/cd-create-prerelease-draft.yml

  publish-prerelease:
    needs:  create-prerelease
    uses: .github/workflows/cd-publish-prerelease.yml
    with:
      latest: true