name: Hotfix Deployment Release

on:
  # push:
  #   branches:
  #     - hotfix
  workflow_dispatch:

jobs:
  deploy-to-dev:
    uses: Matth-Ng/hello-world/.github/workflows/cd-build.yml@hotfix
    
  create-prerelease:
    needs: deploy-to-dev
    uses: Matth-Ng/hello-world/.github/workflows/cd-create-prerelease-draft.yml@hotfix

  publish-prerelease:
    needs: create-prerelease
    env:
      PUBLISH-PRERELEASE: ${{ needs.set-reusable-workflow-var.outputs.PUBLISH-PRERELEASE }}
    uses: Matth-Ng/hello-world/.github/workflows/cd-publish-prerelease.yml@hotfix
    with:
      latest: true

  promote-release:
    needs: publish-prerelease
    uses: Matth-Ng/hello-world/.github/workflows/cd-promote-release.yml@hotfix

  merge-to-main-pr:
    runs-on: ubuntu-latest
    needs: promote-release

    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACTIONS_TOKEN_APP_ID }}
          private_key: ${{ secrets.ACTIONS_TOKEN_PRIVATE_KEY }}

      - name: Create PR
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: POST /repos/{repo}/pulls
          repo: ${{ github.repository }}
          title: "Hot fix"
          head: hotfix
          base: main
          body: "Merging hot fix changes into main"
          maintainer_can_modify: true