name: Merge Main to Hotfix

on:
  schedule:
    - cron: '0 11 * * 3'
  workflow_dispatch:

jobs:
  merge-main-to-hotfix:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Get releases
        id: get-releases
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/releases
          repo: ${{ github.repository }}

      - name: Get Tag
        id: get-tag
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo '${{ steps.get-releases.outputs.data }}' | jq -r 'map(select(.published_at and .prerelease == false)) | first | .target_commitish''

      - name: Merge main
        run: |
          git checkout main
          git pull
          git fetch --tags origin
          git checkout hotfix
          git pull
          git merge ${{ steps.get-tag.outputs.data }}
          git push
