name: Pubish Prerelease

on:
  schedule:
    - cron: '30 10 * * 3'
  workflow_dispatch:
  workflow_call:
    inputs:
      latest:
        required: true
        type: boolean
        default: false
      disable-workflow:
        type: boolean
        default: false
        required: true
    secrets:
      ACTIONS_TOKEN_APP_ID:
        required: true
      ACTIONS_TOKEN_PRIVATE_KEY:
        required: true

jobs:
  get-prerelease:
    runs-on: ubuntu-latest
    outputs:
      RELEASE_ID: ${{ steps.get-prerelease.outputs.value }}
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Get releases
        id: get-releases
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/releases
          repo: ${{ github.repository }}

      - name: release offset
        id: release-offset
        run: |
          echo "::set-output name=offset::nth(1)"
          if [ "${{ inputs.latest }}" ]; then
            echo "latest true"
            echo "::set-output name=offset::first"
          fi

      - name: Get prerelease
        id: get-prerelease
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo "${{ steps.get-releases.outputs.data }}" | jq -r 'map(select(.draft == true and .prerelease == true)) | ${{ steps.release-offset.outputs.offset }} | .id'

  publish-for-staging:
    runs-on: ubuntu-latest
    needs: get-prerelease
    env:
      RELEASE_ID: ${{ needs.get-prerelease.outputs.RELEASE_ID }}

    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.ACTIONS_TOKEN_APP_ID }}
          private_key: ${{ secrets.ACTIONS_TOKEN_PRIVATE_KEY }}

      - name: Update release
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: PATCH /repos/{repo}/releases/{release_id}
          repo: ${{ github.repository }}
          release_id: ${{ env.RELEASE_ID }}
          draft: false
          prerelease: true
      
      - name: Disable workflow boolean
        id: disable-workflow-boolean
        run: |
          echo "::set-output name=boolean::false"
          if [ "${{ inputs.disable-workflow }}" ]; then
            echo "latest true"
            echo "::set-output name=boolean::true"
          fi

      - name: Disable Workflow
        if: ${{ steps.disable-workflow-boolean.outputs.boolean == 'true' }}
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
        with:
          route: PUT /repos/{repo}/actions/workflows/{workflow_id}/disable
          repo: ${{ github.repository }}
          workflow_id: "cd-publish-prerelease.yml"
