name: Staging Build and Push Container

on:
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:

jobs:
  update-staging-manifest:
    runs-on: ubuntu-latest
    environment: 'staging'
    outputs:
      sha-result: ${{ steps.sha-result.outputs.staging-sha }}
    steps:
      - name: Check Staging Ref presence
        id: checksecrets
        shell: bash
        run: |
          if [ "$MULTI_LINE_ARG" == "" ]; then
            echo ::set-output name=secretspresent::false
          else
            echo ::set-output name=secretspresent::true
          fi
        env:
          MULTI_LINE_ARG: ${{ secrets.MULTI_LINE_ARG}}
      - name: do something
        if: steps.checkoutTag.outcome == 'success'
        id: actualWorkStepSuccess
        run: echo "Success____________________________________________________"
      - name: Check Current sha
        run: |
          echo "staging ref: ${{ github.event.client_payload.staging-ref }}"
      - name: Dispatch Utility Ref
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: builds
          client-payload: '{"utility-ref": "${{ github.event.client_payload.staging-ref }}"}'
      - name: Dispatch Utility Ref
        uses: peter-evans/repository-dispatch@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: builds
          client-payload: '{"staging-ref": ""}'