name: Staging Build and Push Container

on:
  workflow_dispatch:

env:
  AWS_ECR_REPO: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/platform-console-ui

jobs:
  update-staging-manifest:
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - name: Checkout by staging-deployment-release-tag
        id: checkoutTag
        uses: actions/checkout@v2
        continue-on-error: false
        with:
          ref: 'staging-deployment-release-tag'
      - name: do something
        if: steps.checkoutTag.outcome == 'success'
        id: actualWorkStepSuccess
        run: echo "Success____________________________________________________"
      - name: Check Current Tag
        run: echo "${{ steps.checkoutTag.outputs }}"
      # - name: Create tag
      #   uses: actions/github-script@v5
      #   with:
      #     script: |
      #       github.rest.git.createRef({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         ref: 'refs/tags/utility-deployment-release-tag',
      #         sha: staging-deployment-release-tag
      #       })
      # - uses: cardinalby/git-tag-action@master
      #   env:
      #     TAG: 'utility-deployment-release-tag'
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Delete delayed-job-tag  
      #   if: steps.actualWorkStepSuccess.outcome == 'success'
      #   uses: dev-drprasad/delete-tag-and-release@v0.2.0
      #   with:
      #     tag_name: 'staging-deployment-release-tag'
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}