name: Staging Build and Push Container

on:
  workflow_dispatch:

env:
  AWS_ECR_REPO: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/platform-console-ui

jobs:
  update-staging-manifest:
    runs-on: ubuntu-latest
    environment: 'staging'
    steps:
      - name: Checkout by staging-deployment-release-tag
        id: checkoutTag
        uses: actions/checkout@v2
        continue-on-error: false
        with:
          ref: 'staging-deployment-release-tag'
      - name: do something
        if: steps.checkoutTag.outcome == 'success'
        id: actualWorkStepSuccess
        run: echo "Success____________________________________________________"
      - name: Rename staging tag to utility tag
        uses: localazy/tag@v1
        with:
          read_key: ${{ secrets.GITHUB_TOKEN }}
          write_key: ${{ secrets.GITHUB_TOKEN }}
          rename_from: 'staging-deployment-release-tag'
          rename_to: 'utility-deployment-release-tag'