name: Staging Build and Push Container

on:
  workflow_dispatch:

env:
  AWS_ECR_REPO: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/platform-console-ui

jobs:
  update-staging-manifest:
    runs-on: ubuntu-latest
    environment: 'staging'
    outputs:
      sha-result: ${{ steps.sha-result.outputs.staging-sha }}
    steps:
      - name: Checkout by staging-deployment-release-tag
        id: checkoutTag
        uses: actions/checkout@v2
        continue-on-error: false
        with:
          ref: 'staging-deployment-release-tag'
      - name: do something
        if: steps.checkoutTag.outcome == 'success'
        id: actualWorkStepSuccess
        run: echo "Success____________________________________________________"
      - name: get sha
        id: sha-result
        shell: bash
        run: |
          echo "::set-output name=staging-sha::$(git rev-list -n 1 staging-deployment-release-tag)"
      - name: Check Current sha
        run: |
          echo "sha: ${{ steps.sha-result.outputs.staging-sha }}"
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/utility-deployment-release-tag',
              sha: ${{ steps.tag-result.outputs.staging-sha }}
            })
      - name: Delete delayed-job-tag  
        if: steps.actualWorkStepSuccess.outcome == 'success'
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          tag_name: 'staging-deployment-release-tag'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}