name: Deploy Release to Utility

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  get-release:
    if: "!github.event.release.draft"
    runs-on: ubuntu-latest
    outputs:
      RELEASE_ID: ${{ steps.get-prerelease.outputs.value }}
      RELEASE_TAG: ${{ steps.get-tag.outputs.value }}
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Get releases
        id: get-releases
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/releases
          repo: ${{ github.repository }}

      - name: Get prerelease
        id: get-prerelease
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo '${{ steps.get-releases.outputs.data }}' | jq -r 'map(select(.published_at)) | first | .id'

      - name: Get Tag
        id: get-tag
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo '${{ steps.get-releases.outputs.data }}' | jq -r 'map(select(.id == ${{ steps.get-prerelease.outputs.value }})) | .target_commitish'

      - name: print variable
        run: |
          echo "${{ steps.get-tag.outputs.value }}"
  
  deploy-prod:
    environment: Utility
    if: "!github.event.release.draft"
    runs-on: ubuntu-latest
    needs: get-release
    env:
      RELEASE_ID: ${{ needs.get-prerelease.outputs.RELEASE_ID }}
      RELEASE_TAG: ${{ needs.get-prerelease.outputs.RELEASE_TAG }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Configure AWS Credentials
        run: |
          echo "updating utility manifest"