name: Create Prerelease

on:
  schedule:
    - cron: '0 12 * * 3'
  workflow_dispatch:
    inputs:
      latest:
        description: 'Check to use current date and time, otherwise default to last Monday'
        type: boolean
        required: false
        default: false
      tag-generate:
        description: 'The previous tag to start the changelog from'
        type: string
        required: false
        default: ''

env:
  AWS_ECR_REPO: 008577686731.dkr.ecr.us-gov-west-1.amazonaws.com/dsva/platform-console-ui

jobs:
  deploy-staging:
    environment: Staging
    runs-on: ubuntu-latest
    outputs:
      RELEASE_SHA: ${{ steps.get-sha.outputs.sha }}
      MONDAY_DATE: ${{ steps.last-week-monday.outputs.date }}
      GET_VERSION: ${{ steps.get-version.outputs.package-version }}
      PREV_RELEASE_TAG: ${{ steps.previous_release_tag.outputs.prev-release-tag }}
    env:
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v3

      - name: Get Recent Date
        shell: bash
        if: "${{ github.event.inputs.latest == 'true' }}"
        run: |
          delimiter=$(date +'%Y-%m-%d')

      - name: Get Last Week Monday
        id: last-week-monday
        if: "${{ github.event.inputs.latest == 'false' }}"
        shell: bash
        run: |
          if $(date +%u) -lt 2; then
            delimiter=$(date +'%Y-%m-%d' -d "last-monday")
          else
            delimiter=$(date +'%Y-%m-%d' -d "last-monday - 1 week")
          fi
          echo "::set-output name=date::$delimiter"

      - name: Get Last Monday Commits
        id: last-monday-commits
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/commits?per_page=1&until=${{ steps.last-week-monday.outputs.date }}T23:59:59Z
          repo: ${{ github.repository }}

      - name: Get SHA
        id: get-sha
        shell: bash
        run: |
          shortSha=$(echo ${{ fromJson(steps.last-monday-commits.outputs.data)[0].sha }} | cut -c1-7)
          echo "::set-output name=sha::${{ fromJson(steps.last-monday-commits.outputs.data)[0].sha }}"
          echo "::set-output name=short-sha::$shortSha"

      - name: Get version
        id: get-version
        shell: bash
        run: |
          if git rev-parse "$(npm run get-version -s)-${{ steps.get-sha.outputs.short-sha }}" >/dev/null 2>&1; then
            package="$(npm run get-version -s)-${{ steps.get-sha.outputs.short-sha }}"
          else
            package="$(npm run get-version -s)-${{ steps.get-sha.outputs.short-sha }}-${{ github.run_number }}"
          fi
          echo "::set-output name=package-version::$package"
      
      - name: Get previous releases
        id: previous-release
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{repo}/releases
          repo: ${{ github.repository }}

      - name: Get previous release tag
        id: previous_release_tag
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.tag-generate }}" == "" ]]; then
            echo "inside empty"
            tag=$(echo ${{ fromJson(steps.previous-release.outputs.data) }}  | jq -r 'map(select(.prerelease)) | first | .tag_name' )
            echo "::set-output name=prev-release-tag::$tag"
          else
            echo "::set-output name=prev-release-tag::"${{ github.event.inputs.tag-generate }}"
          fi

      - name: check variable
        shell: bash
        run: |
          echo "${{ steps.previous_release_tag.outputs.prev-release-tag }}"
          if [["" == ""]]; then
            echo "inside"
          else
            echo "inside"

      - name: Create tag
        id: create-tag
        uses: octokit/request-action@v2.x
        continue-on-error: true
        with:
          route: POST /repos/{repo}/git/refs
          repo: ${{ github.repository }}
          ref: 'refs/tags/${{ steps.get-version.outputs.package-version }}'
          sha: ${{ steps.get-sha.outputs.sha }}

      - name: Generate release notes
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/releases/generate-notes
          repo: ${{ github.repository }}
          tag_name: ${{ steps.get-version.outputs.package-version }}
          previous_tag_name: ${{ steps.previous_release_tag.outputs.prev-release-tag }}
          target_commitish: ${{ steps.get-sha.outputs.sha }}

  update-staging-manifest:
    environment: Staging
    runs-on: ubuntu-latest
    needs: deploy-staging
    env:
      GITHUB_TOKEN: ${{ github.token }}
      RELEASE_SHA: ${{ needs.deploy-staging.outputs.RELEASE_SHA }}

    steps:
      - name: Update Staging Manifest
        run: echo "Updating Staging Manifest"


  update-release-staging:
    environment: Staging
    runs-on: ubuntu-latest
    needs: [deploy-staging, update-staging-manifest]
    env:
      MONDAY_DATE: ${{ needs.deploy-staging.outputs.MONDAY_DATE }}
      RELEASE_SHA: ${{ needs.deploy-staging.outputs.RELEASE_SHA }}
      GET_VERSION: ${{ needs.deploy-staging.outputs.GET_VERSION }}
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Create prerelease
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{repo}/releases
          repo: ${{ github.repository }}
          name: ${{ env.MONDAY_DATE }}-Staging-Utility
          tag_name: ${{ env.GET_VERSION }}
          target_commitish: ${{ env.RELEASE_SHA }}
          generate_release_notes: true
          prerelease: true